<?php

namespace AppBundle\Repository;

/**
 * PairMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PairMapRepository extends \Doctrine\ORM\EntityRepository
{
}
