<?php

namespace AppBundle\Repository;

/**
 * SymbolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymbolPairRepository extends \Doctrine\ORM\EntityRepository
{
}
